apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-secret
type: kubernetes.io/dockerconfigjson
data:
  # generate via: echo -n '{"auths":{"https://index.docker.io/v1/":{"username":"camelcasemm","password":"@tW(m]&8mdKa+5q","email":"markmitchell451@gmail.com"}}}' | base64 -w 0
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJjYW1lbGNhc2VtbSIsInBhc3N3b3JkIjoiQHRXKG1dJjhtZEthKzVxIiwiZW1haWwiOiJtYXJrbWl0Y2hlbGw0NTFAZ21haWwuY29tIn19fQ==
