#!/bin/bash

# kill port forwards generated by skaffold
PROCS_TO_KILL=$(ps -ef | grep -E 'skaffold.*--port-forward' | grep -v grep)

if [ -z "${PROCS_TO_KILL}" ]; then
	exit 0
fi

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

echo -e "${RED}"
echo "______________________________________________"
echo "Killing port forward processes generated by skaffold"
echo "______________________________________________"
echo -e "${NC}"

echo "$PROCS_TO_KILL" | awk '{print $2}' | xargs kill
